### ISSUE TITLE
bcm43xx_init error

### ISSUE THREAD

**Issue by samouds** [resin-io-playground/wifi-connect-ble#1]
Hello,

I'm trying to make wifi-connect-ble work on my rpi 3  (Resin OS 1.24.1 - SUPERVISOR 2.8.3), but I get this error : 

```
28.03.17 15:26:21 (+0200) bcm43xx_init
28.03.17 15:26:31 (+0200) Initialization timed out.
28.03.17 15:26:31 (+0200) bcm43xx_init
28.03.17 15:26:31 (+0200) Cannot open directory '/etc/firmware': No such file or directory
28.03.17 15:26:31 (+0200) Patch not found, continue anyway
28.03.17 15:26:31 (+0200) Set Controller UART speed to 921600 bit/s
28.03.17 15:26:31 (+0200) Device setup complete
```

```
/# sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)
```

And when I look for the bluetooth signal on my phone, I don't see it.

Any idea ?

**Comment by samouds** [comment]
This is the output of **hciconfig status** : 

```
hci0:   Type: BR/EDR  Bus: UART
        BD Address: AA:AA:AA:AA:AA:AA  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:775 acl:0 sco:0 events:47 errors:0
        TX bytes:638 acl:0 sco:0 commands:47 errors:0
```

and **hcitool | grep ver** : 

```
hcitool - HCI Tool ver 5.23
```

**Comment by samouds** [comment]
Hello,

I fix this. The issue comes from my Dockerfile, which is a mix of wifi-connect-ble and resin-electronjs. I just removed theses lines :  

```
RUN sed -i "s!httpredir.debian.org!`curl -s -D - http://httpredir.debian.org/demo/debian/ | awk '/^Link:/ { print $2 }' | sed -e 's@<http://\(.*\)/debian/>;@\1@g'`!" /etc/apt/sources.list

COPY debian-pinning /etc/apt/preferences.d/

ENV DEBIAN_FRONTEND noninteractive
```

**Comment by imrehg** [comment]
Hi yes, this actually makes good sense, probably the only thing you needed to remove is the `COPY debian-pinning /etc/apt/preferences.d/` line. That pinning file probably prevented the correct bluetooth firmware to be installed from the raspbian repositories. Indeed, this is a difficulty of combining code from two projects.

**Comment by samouds** [comment]
thanks @imrehg ! indeed it works now. We should be careful with that :)

One question, why you need this pinning in the electronjs project ?

**Comment by imrehg** [comment]
@samouds if I read this PR correctly https://github.com/resin-io/resin-electronjs/pull/28 then the reason was that resin-electronjs works across other devices as well, and making sure that the tested packages are the same across all devices (so the Raspberry Pis pulls from Debian by default as well). Otherwise you might end up with a lot of strange dependency issues.
